# Generated by Django 2.1.7 on 2019-03-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=256)),
                ('environment_variable', models.TextField()),
                ('stack_file', models.TextField()),
                ('stack_id', models.IntegerField(blank=True, null=True)),
                ('resource_control_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
