# Generated by Django 2.1.7 on 2019-03-19 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stack',
            old_name='environment_variables',
            new_name='environment_variable',
        ),
    ]
